# Generated by Django 4.0.5 on 2022-11-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
