# Generated by Django 4.0.5 on 2022-11-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_basicinfo_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='profile',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
