# Generated by Django 4.0.5 on 2022-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_basicinfo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
