# Generated by Django 4.0.5 on 2022-11-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_aboutme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='about_me',
            new_name='aboutme',
        ),
    ]
