# Generated by Django 4.0.5 on 2022-11-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_about_me_aboutme_aboutme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='aboutme',
            field=models.TextField(),
        ),
    ]
