# Generated by Django 4.0.5 on 2022-11-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_data',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_data',
            field=models.CharField(max_length=255),
        ),
    ]
