# Generated by Django 4.0.5 on 2022-11-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_workexperience_end_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
